//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaskeWEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bruger
    {
        public Bruger()
        {
            this.Betalings = new HashSet<Betaling>();
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int Id { get; set; }
        public string Navn { get; set; }
        public Nullable<decimal> Konto { get; set; }
        public Nullable<int> VaskeriId { get; set; }
    
        public virtual ICollection<Betaling> Betalings { get; set; }
        public virtual Vaskeri Vaskeri { get; set; }
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
