//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaskeWEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaskeTid
    {
        public VaskeTid()
        {
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Starttid { get; set; }
        public Nullable<System.DateTime> Sluttid { get; set; }
        public Nullable<bool> VaskStarted { get; set; }
        public Nullable<int> VaskeriId { get; set; }
    
        public virtual ICollection<Reservation> Reservations { get; set; }
        public virtual Vaskeri Vaskeri { get; set; }
    }
}
