//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vaskeProjekt
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VaskeProjektEntities1 : DbContext
    {
        public VaskeProjektEntities1()
            : base("name=VaskeProjektEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Betaling> Betalings { get; set; }
        public DbSet<Bruger> Brugers { get; set; }
        public DbSet<Maskine> Maskines { get; set; }
        public DbSet<Reservation> Reservations { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<VaskeProgram> VaskePrograms { get; set; }
        public DbSet<Vaskeri> Vaskeris { get; set; }
        public DbSet<VaskeTid> VaskeTids { get; set; }
    }
}
