//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vaskeProjekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaskeProgram
    {
        public int Id { get; set; }
        public Nullable<int> Pris { get; set; }
        public Nullable<int> Tid { get; set; }
        public Nullable<int> MaskineId { get; set; }
        public Nullable<int> OrderId { get; set; }
    
        public virtual Betaling Betaling { get; set; }
        public virtual Maskine Maskine { get; set; }
    }
}
